[package]
name = "spintable"
version = "0.2.0"
authors = ["ex0dus-0x <ex0dus@codemuch.tech>"]

[dependencies]
curl = "0.4.8"
clap = "2.26.0"
libc = "0.2"
prettytable-rs = "0.6.7"
termion = "1"
mpv = "0.2.3"
pbr = "1.0.0"
serde = "1.0.12"
serde_json = "1.0"
serde_derive = "1.0.12"