[package]
name = "spintable"
version = "0.3.0"
authors = ["ex0dus-0x <ex0dus@codemuch.tech>"]

[dependencies]
reqwest = "0.8.2"
clap = "2.26.0"
termion = "1"
mpv = "0.2.3"
serde = "1.0.12"
serde_json = "1.0"
serde_derive = "1.0.12"