[package]
name = "spintable"
version = "0.2.0"
authors = ["ex0dus-0x <ex0dus@codemuch.tech>"]

[dependencies]
curl = "0.4.8"
regex = "0.2"
clap = "2.26.0"
serde = "1.0.12"
serde_json = "1.0"
serde_derive = "1.0.12"